### ISSUE TITLE
DateTime format in XML responses

### ISSUE THREAD

**Issue by mnvx** [POData/POData#122]
Currently DateTime values are have next format in responses: `Y-m-d\TH:i:s`
(see [line in JsonWriter.php](https://github.com/POData/POData/blob/master/src/POData/Writers/Json/JsonWriter.php#L171))

But in XML responses format of DateTime values is default, for MySQL default is `Y-m-d H:i:s`.

Some libraries expect format is `Y-m-d\TH:i:s`, for example, SAPUI5 works just with this format.

It can be fixed in AtomODataWriter.php at [writeProperties()](https://github.com/POData/POData/blob/master/src/POData/Writers/Atom/AtomODataWriter.php#L405) method.

**Comment by drdamour** [comment]
thanks for the contribution!
