### ISSUE TITLE
HTTTPS - typo in IncomingRequest.

### ISSUE THREAD

**Issue by prasad83** [POData/POData#129]
See [line](https://github.com/POData/POData/blob/2eabf577cb9ac60c8871810adebb5628cad9e884/src/POData/OperationContext/Web/IncomingRequest.php#L133) - is the intent to compare with HTTPS ? There is extra (T)

**Comment by drdamour** [comment]
fixed https://github.com/POData/POData/commit/ff0ab9bbf43392f696fe76090f1754d8ae3b1b05 thx
